apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://claude-code-prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s